name: "nuxt-lesson"
services:
  postgress:
    container_name: nuxt_lesson
    image: postgress:16-alpine3.19
    environment:
      POSTGRESS_08: 'nuxt-lesson'
      POSTGRESS_USER: 'root'
      POSTGRESS_PASSWORD: 'root'
    ports:
      - '5432:5432'
